services:
  app-camere:
    build: .
    container_name: server_camere_web
    restart: always
    volumes:
      - .:/app
     # - /media/miruna:/media/miruna
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok_tunel
    restart: always
    command:
      - "http"
      - "--authtoken=${NGROK_AUTHTOKEN}"
      - "http://server_camere_web:5000"
    depends_on:
      - app-camere
  motor_procesare:
    build: .
    container_name: motor_procesare_bg
    restart: always
    volumes:
      - .:/app
      - /media/miruna:/media/miruna
    command: python main.py
    environment:
      - TZ=Europe/Bucharest